version: "3.8"

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: jammy-20230308
    init: true
    privileged: true
    command: sleep infinity
    volumes:
      - ..:/home/vscode/workspace:cached
    
