version: "3.8"

services:
  ubuntu:
    build: 
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: jammy-20230308
    init: true
    privileged: true
    command: sleep infinity
    volumes:
      - ..:/home/vscode/workspace:cached
    

  # postgres1:
  #   image: postgres:latest
  #   environment:
  #     POSGRES_DB: metabase
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #   ports:
  #     - 5432:5432

  # metabase_base:
  #   image: metabase/metabase:latest
  #   environment:
  #     MB_DB_TYPE=postgres
  #     MB_DB_DBNAME=metabase
  #     MB_DB_PORT=5432
  #     MB_DB_USER=postgres
  #     MB_DB_PASS=postgres
  #     MB_DB_HOST=postgres1
  #   ports:
  #     - 3000:3000